source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DropDownMenu_Example', :exclusive => true do
  pod "DropDownMenu", :path => "../"
end

target 'DropDownMenu_Tests', :exclusive => true do
  pod "DropDownMenu", :path => "../"

  
end
